[package]
name = "compliance_check"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.9", directory = "noir-projects/aztec-nr/aztec" }