[package]
name = "token_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.9", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { path = "../libs/uint-note" }
balance_set = { path = "../libs/balance-set" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.9", directory = "noir-projects/aztec-nr/authwit" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.9", directory = "noir-projects/aztec-nr/compressed-string" }
contract_instance_deployer = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0-alpha-testnet.9", directory = "noir-projects/noir-contracts/contracts/protocol/contract_instance_deployer_contract" }
