name: Canary Release

on: workflow_dispatch

jobs:
  export:
    name: Generate Canary Release
    environment: prod
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: '@defi-wonderland/aztec-standards'
      AZTEC_VERSION: 0.85.0-alpha-testnet.7

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Aztec CLI
        run: |
          curl -s https://install.aztec.network > tmp.sh
          bash tmp.sh <<< yes "yes"

      - name: Update path
        run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH

      - name: Set Aztec version
        run: |
          VERSION=${AZTEC_VERSION} aztec-up
      
      - name: Compile
        run: yarn compile

      - name: Codegen
        run: aztec codegen target --outdir artifacts

      # Install the current canary version of the package we're releasing now.
      - name: Install dependencies
        run: yarn add @defi-wonderland/aztec-standards@canary

      - name: Update version
        run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version

      # TODO: We do several things here:
      # 1. Create current and historical directories
      # 2. Copy historical versions from existing package
      # 3. Move this version's artifacts and circuits to current/
      # 4. Move this version's artifact and circuit to historical/ as well.
      # 5. Copy package.json, README.md, and LICENSE to current/
      - name: Prepare files for release
        run: |
          VERSION="0.0.0-${GITHUB_SHA::8}"
          mkdir -p export/${{ env.PROJECT_NAME }}/current
          mkdir -p export/${{ env.PROJECT_NAME }}/historical
          
          if [ -d "node_modules/${{ env.PROJECT_NAME }}/historical" ]; then
            cp -r node_modules/${{ env.PROJECT_NAME }}/historical/* export/${{ env.PROJECT_NAME }}/historical/
          else
            echo "No historical directory found, skipping copy"
          fi
          
          cp -r artifacts export/${{ env.PROJECT_NAME }}/current/
          cp -r target export/${{ env.PROJECT_NAME }}/current/
        
          cp -r export/${{ env.PROJECT_NAME }}/current export/${{ env.PROJECT_NAME }}/historical/$VERSION

          cp package.json export/${{ env.PROJECT_NAME }}/
          cp README.md export/${{ env.PROJECT_NAME }}/
          cp LICENSE export/${{ env.PROJECT_NAME }}/


      - name: Publish to NPM
        run: cd export/${{ env.PROJECT_NAME }}/current && npm publish --access public --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}